name: Terraform Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Format
        run: terraform fmt -check -recursive
      - name: Terraform Validate
        run: terraform validate
      - name: TFLint
        uses: terraform-linters/setup-tflint@v1
      - name: Run TFLint
        run: tflint --init && tflint
      - name: Checkov Security Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./terraform
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && success()
        run: terraform apply -auto-approve
      - name: Terratest
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run Terratest
        run: |
          cd test/terratest
          go test -v -coverprofile=coverage.out -covermode=atomic
          go tool cover -func=coverage.out | grep -E 'total:' | awk '{print $3}' | grep -qE '([6-9][0-9]|100)\.\d+%' || exit 1
